## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
history_filter = [
  "--help",
  "--version",
  "-h",
  "-v",
  "^cat ",
  "^cd ",
  "^clear",
  "^ls ",
  "^nvim ",
  "^rm",
  "^task",
  "^tmux",
  "^where ",
  "^which ",
  "^z ",
]
