[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/code/"
desc = "Go to code directory"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/dotfiles/"
desc = "Go to dotfiles directory"

[mgr]
show_hidden = "show"
